# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pCi3VTnTgcXyUx83oPQMb0sbwj7w8bjj
"""

import streamlit as st

# Streamlit app
st.title("Maize Crop Price Prediction")
st.sidebar.header("Input Parameters")

# User inputs
region = st.sidebar.selectbox("Region", data['Regions'].unique())
year = st.sidebar.selectbox("Year", data['Year'].unique())
month = st.sidebar.selectbox("Month", data['Month'].unique())

# Prepare input data for prediction
input_data = pd.DataFrame({
    'Month': [month],
    'Year': [year],
    'Regions': [region],
    'Annual Rainfall': [data['Annual Rainfall'].mean()],  # Replace with actual data or user input
    'Annual Temperature': [data['Annual Temperature'].mean()]  # Replace with actual data or user input
})

input_data = pd.get_dummies(input_data, columns=['Regions'], drop_first=True)

# Ensure the input data has the same columns as the training data
for col in X.columns:
    if col not in input_data.columns:
        input_data[col] = 0

# Predict using the ANN model
predicted_price = model.predict(input_data)[0][0]
st.write(f"Predicted Maize Price: {predicted_price} KES")

# Data visualization
st.line_chart(data.groupby('Year')['Price'].mean())